#!/usr/bin/env python3
"""
根据 agent.py 和数据文件自动生成 judge.py。

Usage:
    python generate_judge.py --input-dir /path/to/inputs --task-type mle --output /path/to/judge.py
    python generate_judge.py --input-dir /path/to/inputs --task-type mle --metrics rmse,rrmse,mape
"""
from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional


DEFAULT_MLE_METRICS = ["rmse", "mape"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate judge.py for AlphaEvolve")
    parser.add_argument("--input-dir", required=True, help="Path to input directory")
    parser.add_argument("--task-type", required=True, choices=["mle", "prompt"], help="Task type")
    parser.add_argument("--output", help="Output path (default: <input-dir>/judge.py)")
    parser.add_argument("--dry-run", action="store_true", help="Print generated code without writing")
    parser.add_argument("--metrics", help="Comma-separated metric keys for MLE combined_score")
    return parser.parse_args()


def analyze_agent_return(agent_path: Path) -> Optional[List[str]]:
    """分析 agent.py 的 main 函数返回的 metrics 字段"""
    try:
        source = agent_path.read_text(encoding="utf-8")
        tree = ast.parse(source)
        
        # 查找 main 函数中的 return 语句
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "main":
                for child in ast.walk(node):
                    if isinstance(child, ast.Return) and child.value:
                        # 尝试解析 dict 字面量
                        if isinstance(child.value, ast.Dict):
                            keys = []
                            for k in child.value.keys:
                                if isinstance(k, ast.Constant):
                                    keys.append(k.value)
                                elif isinstance(k, ast.Str):  # Python 3.7 兼容
                                    keys.append(k.s)
                            return keys
        return None
    except Exception:
        return None


def analyze_data_columns(data_path: Path) -> Optional[List[str]]:
    """分析数据文件的列名"""
    try:
        if data_path.suffix == ".csv":
            import csv
            with open(data_path, "r", encoding="utf-8") as f:
                reader = csv.reader(f)
                headers = next(reader, None)
                return headers
        elif data_path.suffix == ".jsonl":
            with open(data_path, "r", encoding="utf-8") as f:
                line = f.readline().strip()
                if line:
                    data = json.loads(line)
                    return list(data.keys())
        return None
    except Exception:
        return None


def generate_mle_judge(input_dir: Path, metrics: Optional[List[str]] = None) -> str:
    """生成 MLE 任务的 judge.py"""
    
    # 默认 metrics
    if not metrics:
        metrics = list(DEFAULT_MLE_METRICS)
    
    # 生成 combined_score 计算逻辑
    score_parts = []
    for m in metrics:
        m_lower = m.lower()
        if "rrmse" in m_lower or "mape" in m_lower or m_lower.endswith("_pct"):
            score_parts.append(
                f'    score_{m} = 1.0 / (1.0 + float(metrics.get("{m}", float("inf"))) / 100.0)'
            )
        else:
            score_parts.append(
                f'    score_{m} = 1.0 / (1.0 + float(metrics.get("{m}", float("inf"))))'
            )
    score_combination = " + ".join([f"score_{m}" for m in metrics])
    score_divisor = float(len(metrics))
    
    template = f'''"""
AlphaEvolve evaluator for MLE task.
Auto-generated by generate_judge.py
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, Dict

from openevolve.evaluation_result import EvaluationResult

ROOT = Path(__file__).resolve().parent


def _load_module(program_path: str):
    """动态加载候选程序模块"""
    module_name = f"candidate_module_{{Path(program_path).stem}}"
    spec = importlib.util.spec_from_file_location(module_name, program_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load module from {{program_path}}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def calculate_combined_score(metrics: Dict[str, Any]) -> float:
    """将原始指标转换为 combined_score (0~1, 且>0)，指标 key 需与 agent.py 返回一致"""
{chr(10).join(score_parts)}
    
    combined = ({score_combination}) / {score_divisor}
    return max(1e-12, min(1.0, combined))


def evaluate(program_path: str) -> EvaluationResult:
    """
    AlphaEvolve 评估入口
    
    Args:
        program_path: 候选程序路径
    
    Returns:
        EvaluationResult with combined_score
    """
    try:
        module = _load_module(program_path)
        
        if not hasattr(module, "main"):
            return EvaluationResult(
                metrics={{"combined_score": 0.0, "error": "main(root) not found"}}
            )
        
        # 调用候选程序的 main 函数，传入数据目录
        raw_metrics = module.main(ROOT)
        
        # 计算 combined_score
        combined = calculate_combined_score(raw_metrics)
        
        metrics = {{
            "combined_score": combined,
            **raw_metrics,
        }}
        
        print(f"✅ Evaluation results: {{metrics}}")
        return EvaluationResult(metrics=metrics)
        
    except Exception as e:
        print(f"❌ Evaluation error: {{e}}")
        return EvaluationResult(
            metrics={{"combined_score": 0.0, "error": str(e)}}
        )


if __name__ == "__main__":
    # 本地测试
    result = evaluate(str(ROOT / "agent.py"))
    print(f"Evaluation Result: {{result}}")
'''
    return template


def generate_prompt_judge(input_dir: Path) -> str:
    """生成 Prompt 任务的 judge.py"""
    
    template = '''"""
AlphaEvolve evaluator for Prompt task.
Auto-generated by generate_judge.py
"""
from __future__ import annotations

import importlib.util
import json
import logging
import os
import sys
from pathlib import Path
from statistics import mean
from typing import Any, Dict, List

from openevolve.evaluation_result import EvaluationResult

ROOT = Path(__file__).resolve().parent
TRAIN_PATH = ROOT / "train.jsonl"
TEST_PATH = ROOT / "test.jsonl"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


def _load_module(program_path: str):
    """动态加载候选程序模块"""
    module_name = f"candidate_module_{Path(program_path).stem}"
    spec = importlib.util.spec_from_file_location(module_name, program_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load module from {program_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    """读取 JSONL 文件"""
    items = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    return items


def evaluate(program_path: str) -> EvaluationResult:
    """
    AlphaEvolve 评估入口
    """
    try:
        # 导入生成和评估模块（用户提供）
        sys.path.insert(0, str(ROOT))
        from generate_press_agent import generate_press_agent
        from evaluate_press_agent import evaluate_press_agent
        
        # 加载候选程序
        module = _load_module(program_path)
        
        if not hasattr(module, "get_prompt_generate_press"):
            return EvaluationResult(
                metrics={"combined_score": 0.0, "error": "get_prompt_generate_press() not found"}
            )
        
        system_prompt, user_prompt_template = module.get_prompt_generate_press()
        log.info("Loaded prompt, length=%d", len(system_prompt))
        
        # 读取训练数据
        train_data = _read_jsonl(TRAIN_PATH)
        log.info("Loaded %d training samples", len(train_data))
        
        # 评估每个样本
        scores = []
        for idx, sample in enumerate(train_data):
            try:
                # 格式化 user prompt
                user_prompt = user_prompt_template.format(
                    interview_type=sample.get("interview_type", ""),
                    interview_context=sample.get("interview_context", ""),
                )
                
                # 生成内容
                generated = generate_press_agent(
                    model_name=os.getenv("GENERATE_MODEL", "gpt-4"),
                    system_prompt=system_prompt,
                    user_prompt=user_prompt,
                )
                
                # 评估生成内容
                result = evaluate_press_agent(
                    model_name=os.getenv("EVALUATE_MODEL", "gpt-4"),
                    generated_press=generated,
                    reference_press=sample.get("ground_truth", ""),
                )
                
                score = result.get("combined_score", 0.0)
                scores.append(score)
                log.info("Sample %d: score=%.4f", idx, score)
                
            except Exception as e:
                log.error("Sample %d failed: %s", idx, e)
                scores.append(0.0)
        
        combined = mean(scores) if scores else 0.0
        log.info("Final combined_score: %.4f", combined)
        
        return EvaluationResult(
            metrics={"combined_score": combined, "num_samples": len(scores)}
        )
        
    except Exception as e:
        log.error("Evaluation error: %s", e)
        return EvaluationResult(
            metrics={"combined_score": 0.0, "error": str(e)}
        )


if __name__ == "__main__":
    result = evaluate(str(ROOT / "agent.py"))
    print(f"Evaluation Result: {result}")
'''
    return template


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir).resolve()
    output_path = Path(args.output) if args.output else input_dir / "judge.py"
    
    agent_path = input_dir / "agent.py"
    if not agent_path.exists():
        print(f"[ERROR] agent.py not found: {agent_path}")
        return 1
    
    # 生成 judge.py
    if args.task_type == "mle":
        metrics = None
        if args.metrics:
            metrics = [m.strip() for m in args.metrics.split(",") if m.strip()]
            print(f"[INFO] Using metrics from --metrics: {metrics}")
        else:
            metrics = analyze_agent_return(agent_path)
            if metrics:
                print(f"[INFO] Detected metrics from agent.py: {metrics}")
            else:
                print("[ERROR] Could not detect metrics from agent.py; pass --metrics")
                return 2

        code = generate_mle_judge(input_dir, metrics)
    else:
        code = generate_prompt_judge(input_dir)
    
    if args.dry_run:
        print("[DRY RUN] Generated judge.py:")
        print("=" * 60)
        print(code)
        print("=" * 60)
    else:
        output_path.write_text(code, encoding="utf-8")
        print(f"[OK] Generated judge.py: {output_path}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
